provider: local
ClusterLoader:
  cleanup: false
  projects:
    - num: 1
      basename: clusterloader-perfapp
      ifexists: delete
      tuning: default
      templates:
        - num: 200
          file: perf-app.yml
  tuningsets:
    - name: default
      templates:
        stepping:
          stepsize: 50
          pause: 5
          timeout: 10
        rate_limit:
          delay: 0

