name: perfapp CI

on:
  push:
    branches: [ master ]

jobs:

  build-master:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        golang-version: [1.19]
        arch:
         - arm64
         - amd64
         - ppc64le
         - s390x

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install qemu-user-static fuse-overlayfs -y
        sudo apt-get install podman -y
      if: runner.os == 'Linux'

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.golang-version }}

    - name: Login in quay
      run: podman login quay.io -u ${QUAY_USER} -p ${QUAY_TOKEN}
      env:
        QUAY_USER: ${{ secrets.QUAY_USER }}
        QUAY_TOKEN: ${{ secrets.QUAY_TOKEN }}

    - name: Build binary and Publish Multi-Arch container
      run: ARCH=${{ matrix.arch }} make
